"""Protocol-preserving loader for official LPShift generated datasets.

The adapter deliberately keeps the message-passing graph separate from the
label split. It does not filter duplicate candidates or repair the official
false-negative cases.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import torch


def sha256_array(value: np.ndarray | torch.Tensor) -> str:
    if isinstance(value, torch.Tensor):
        value = value.detach().cpu().numpy()
    array = np.ascontiguousarray(value)
    return hashlib.sha256(array.tobytes()).hexdigest()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def canonical_keys(edges: np.ndarray | torch.Tensor) -> set[tuple[int, int]]:
    if isinstance(edges, torch.Tensor):
        edges = edges.detach().cpu().numpy()
    rows = np.asarray(edges, dtype=np.int64).reshape(-1, 2)
    return {(min(int(u), int(v)), max(int(u), int(v))) for u, v in rows}


@dataclass
class LPShiftData:
    dataset_name: str
    root: Path
    data: object
    split: dict

    @property
    def dataset_dir(self) -> Path:
        return self.root / "dataset" / (self.dataset_name + "Dataset")

    @property
    def num_nodes(self) -> int:
        return int(self.data.num_nodes)

    @property
    def features(self) -> torch.Tensor:
        return self.data.x

    @property
    def message_edge_index(self) -> torch.Tensor:
        # This is the exact edge_index saved by LPShift. Do not rebuild it
        # from train positives: it contains additional context edges.
        return self.data.edge_index

    @property
    def train_pos(self) -> torch.Tensor:
        return self.split["train"]["edge"]

    @property
    def valid_pos(self) -> torch.Tensor:
        return self.split["valid"]["edge"]

    @property
    def test_pos(self) -> torch.Tensor:
        return self.split["test"]["edge"]

    @property
    def valid_neg(self) -> torch.Tensor:
        return self.split["valid"]["edge_neg"]

    @property
    def test_neg(self) -> torch.Tensor:
        return self.split["test"]["edge_neg"]

    @classmethod
    def load(cls, root: str | Path, dataset_name: str) -> "LPShiftData":
        root = Path(root)
        directory = root / "dataset" / (dataset_name + "Dataset")
        data_path = directory / (dataset_name + "Dataset.pt")
        split_path = directory / (dataset_name + "Dataset_split.pt")
        if not data_path.exists() or not split_path.exists():
            raise FileNotFoundError(f"LPShift files missing under {directory}")
        # Official local files are trusted artifacts generated by gen_synth.py.
        data = torch.load(data_path, map_location="cpu", weights_only=False)
        split = torch.load(split_path, map_location="cpu", weights_only=False)
        return cls(dataset_name, root, data, split)

    def summary(self) -> dict:
        return {
            "dataset_name": self.dataset_name,
            "num_nodes": self.num_nodes,
            "feature_shape": list(self.features.shape),
            "message_edge_index_shape": list(self.message_edge_index.shape),
            "message_edge_index_hash": sha256_array(self.message_edge_index),
            "train_pos_shape": list(self.train_pos.shape),
            "valid_pos_shape": list(self.valid_pos.shape),
            "test_pos_shape": list(self.test_pos.shape),
            "valid_neg_shape": list(self.valid_neg.shape),
            "test_neg_shape": list(self.test_neg.shape),
            "train_pos_hash": sha256_array(self.train_pos),
            "valid_pos_hash": sha256_array(self.valid_pos),
            "test_pos_hash": sha256_array(self.test_pos),
            "valid_neg_hash": sha256_array(self.valid_neg),
            "test_neg_hash": sha256_array(self.test_neg),
            "valid_neg_file_hash": sha256_file(self.dataset_dir / "heart_valid_samples.npy"),
            "test_neg_file_hash": sha256_file(self.dataset_dir / "heart_test_samples.npy"),
        }

    def message_edge_keys(self) -> set[tuple[int, int]]:
        return canonical_keys(self.message_edge_index.t())

    def message_neighbors(self) -> list[set[int]]:
        neighbors = [set() for _ in range(self.num_nodes)]
        for u, v in self.message_edge_index.detach().cpu().t().tolist():
            u, v = int(u), int(v)
            if u == v:
                continue
            neighbors[u].add(v)
            neighbors[v].add(u)
        return neighbors

    @staticmethod
    def mask_target_edges(edge_index: torch.Tensor, pairs: torch.Tensor) -> torch.Tensor:
        """Remove both directions of every target pair from a directed list."""
        if edge_index.numel() == 0 or pairs.numel() == 0:
            return edge_index
        edge_low = torch.minimum(edge_index[0], edge_index[1])
        edge_high = torch.maximum(edge_index[0], edge_index[1])
        pair_low = torch.minimum(pairs[:, 0], pairs[:, 1])
        pair_high = torch.maximum(pairs[:, 0], pairs[:, 1])
        base = int(max(int(edge_high.max().item()), int(pair_high.max().item())) + 1)
        edge_keys = edge_low * base + edge_high
        pair_keys = pair_low * base + pair_high
        return edge_index[:, ~torch.isin(edge_keys, pair_keys)]

    def training_view(self) -> dict[str, torch.Tensor]:
        """Fields allowed to the training sampler/model before evaluation."""
        return {
            "message_edge_index": self.message_edge_index,
            "train_pos": self.train_pos,
        }


def save_summary(adapter: LPShiftData, output: str | Path) -> None:
    path = Path(output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(adapter.summary(), indent=2), encoding="utf-8")

