from pathlib import Path
import json,shutil,hashlib,zipfile
root=Path(r'E:\我的资料库\Documents\Downloads\DCDLP-main\HYPERGRAPH_RESEARCH\R_HSPE_STRONG_BACKBONE_V17_4');(root/'scripts').mkdir(parents=True,exist_ok=True)
docs={
'00_AUDIT.md':'''# Frozen method and backbone audit

The V17.2 R-HSPE frozen source, config and entire frozen artifact tree are hashed in AUDIT.json. All37 runtime source files and official NCN repository files are checked against V17.2/V17.3 recorded hashes. No frozen artifact is edited. Prior V17.3 benchmark COMPLETE,45/45 jobs, competitiveness WEAK is the starting evidence.

Host source: NeuralCommonNeighbor commit11d597013750da17ce7468e344bec756a7af39a4, official classes/parameters/graph projection and V17.3 benchmark173.py official_ncn(), NCFG, exact train() AST reused. Any source mismatch stops execution. Train graph, features, validation candidates and frozen metric evaluator use original V17.3 input files. Main preflight reads only Cora/PubMed train/validation fields; test arrays are not loaded until formal promotion. No Citeseer training/preparation until formal Cora+PubMed passes.

Baseline reuse is NOT_ALLOWED here: V17.3 NCN/NCNC trained100epochs, while V17.4 explicitly requires5epoch screen and10epoch final confirmation. Baselines rerun at matching budget. V17.4 also explicitly specifies final10epoch integration checkpoint; all arms evaluate fixed final epoch5/10, retaining epoch-by-epoch validation diagnostically, without best-epoch substitution. These explicit V17.4 overrides are documented; all other host hyperparameters and training logic remain the audited V17.3 values.

Training only uses the training-visible graph. Official PyG negative_sampling and PermIterator unchanged. Precomputed negative schedules use exactly the same installed official sampler calls and seed; runtime sampler is not replaced and every output is asserted bitwise equal to precomputation. The sampler uses Python random.sample and no torch RNG. Cache contains only these train-allowed negatives. No alternative pool or QTHS modification is introduced: host protocol uses its original uniform sampler; frozen R-HSPE method transfers to that host protocol.

Within each host/seed, assert initial encoder+predictor parameter hashes equal, exact per-epoch negatives/permutations equal, and CUDA RNG traces equal before interpreting any promotion. Extra module construction uses fork_rng to preserve torch CPU/CUDA state. Startup audit caught that PubMed's auxiliary frozen loader consumes Python RNG. Corrected loader order: load before common set_seed/random.seed, then construct host and residual. No method/sampler/hyperparameter changes. Invalid job stopped before optimization; its error/log retained in startup_history. Successful earlier Cora pairs passed full RNG/negative/parameter audit and are reused.

Initialization additive equality must have max absolute difference<=5e-7 and residual output exactly zero. All plugin/null added parameter counts must equal75; source/reference module shapes6->8->18->1 checked.
''',
'01_INTEGRATION.md':'''# Single allowed additive integration

s_final(u,v)=s_host(u,v)+delta_R_HSPE(u,v), applied once outside official predictor. NCNC completion recursion remains wholly inside official NCNC; the residual is not inserted into recursive completion scores, common-neighbor representation or message passing.

The independent residual reuses the actual frozen constructor's nhmc_encoder and nhmc_residual nn.Linear modules; frozen pooling function _pool_nhmc is called directly. Actual frozen V17.2 feature constructor make_features builds raw-star candidate(w,e,f) tokens with exact hyperedge identity multiplicity, individual predicted-training-edge masking, train-only right-continuous ECDF, descriptors[a+b,abs(a-b),a*b,0,0,0], shared support, mean/max pooling and log1p counts. Hidden8, Linear6->8+ReLU, mean/max+two counts, zero-initialized Linear18->1;75parameters. Definition and hyperparameters frozen; weights jointly learned.

New sampled training negatives require additional feature-cache rows; they are generated by the same frozen function, not a changed token method. Cora/PubMed validation keys/offsets/support/rank descriptors compared bitwise to frozen V17.1/V17.2 validation cache. Original frozen train-positive target masking is preserved per candidate; host's official batch target masking is unchanged. ECDF fits active training-visible raw-star sizes only, never negative samples or heldout incidence.

C2 null has the same actual frozen Linear modules,75 trainable parameters and two-layer depth. Each candidate gets one constant all-ones6vector; encoded constant is duplicated for mean/max slots, and explicit final two entries are constant ones. Input values never use tokens/support/degrees/size ranks/candidate topology; candidate tensor contributes batch shape and device only. It can learn generic calibration.

Optimizer is original two-group Adam: host encoder at original gnnlr, official predictor plus75 residual parameters at original prelr. Both groups have unchanged defaults; no residual LR/weight/fusion coefficient search. Exact host dropout, widths256, mplayers1, predictor3, target masking, epoch examples, sampling and permutation rules retained. Extra encoder has no dropout/RNG during forward.

Arms N0 NCN, N1 NCN+R-HSPE, C0 NCNC, C1 NCNC+R-HSPE, C2 NCNC+constant-null. PhaseA Cora/PubMed seeds0..2x5epoch validation; only both datasets satisfy requested NCNC and null gates promote. PhaseB seeds0..4x10epochs validation, primary4/5positive+mean/median>0, null>=3/5positive+mean>0. Citeseer only after formal dual pass, seeds0..2x10epochs C0/C1/C2; support primary>=2/3andmean>0. All four metrics retained. No absolute+.002 promotion gate.

After formal dual pass, freeze configuration and final checkpoint hashes before one-shot test. Test Cora/PubMed5seedsC0/C1/C2, NCN pair if formal NCN mean gain positive in both datasets; Citeseer only if validation gate passed. Test primary consistency gates Cora4/5, PubMed3/5, Citeseer2/3, mean positive and median positive for Cora/PubMed. No post-test changes.

Paired traces establish controlled host/seed contrasts; consistency gates do not constitute a formal statistical significance test. The requested STATISTICALLY_DIRECTIONAL_BUT_SMALL flag is descriptive if positive formal mean gain<.002, not a hard threshold and not a claim of a computed p-value.

Automatic supervisor runs at most two GPU jobs and one24-worker CPU feature construction, allowing construction overlap with training. Frozen caches are reused after checksum/definition audit. Measured train/validation/test timing, feature-cache time, GPU peaks, added75parameters and host-relative overhead are emitted automatically. Server-side operations are offline; all new scripts transferred locally. Final report helper only generates artifact fields after the supervisor stops; it starts no experiments.

Final main table retains V17.3 anchors with explicit100/5000/10epoch budgets and adds10epoch plugin and matched host rows; descriptive ranking can include these disclosed budgets. Matched10epoch table is separately retained for direct plugin conclusions. No SOTA/size-causality claim; context-driven interpretation continues.
'''
}
for name,text in docs.items():(root/name).write_text(text,encoding='utf8')
for script in ('strong174.py','finish174.py'):shutil.copyfile(str(Path(r'E:\Z')/script),str(root/'scripts'/script))
shutil.copyfile(r'E:\CodexStorage\Home\attachments\4c03b706-16c0-47dd-895d-c7a2192d9590\已粘贴的文本.txt',str(root/'TASK_V17_4.md'))
with zipfile.ZipFile(r'E:\Z\strong174_docs.zip','w',zipfile.ZIP_DEFLATED) as z:
 for name in list(docs)+['TASK_V17_4.md']:z.write(str(root/name),name)
print('V17.4 audit/integration docs ready')
