import hashlib,json
from pathlib import Path
R=Path(r'E:\我的资料库\Documents\Downloads\DCDLP-main'); O=R/'PAPER_PREP/R_HSPE_DSR_MANUSCRIPT_V2'; AD=O/'audit_sources/DSR_V32'
(O/'TITLE_OPTIONS.md').write_text('''# Title options (not finalized)\n\n1. **Dynamic Structural Routing with Hyperedge-Pair Context for Link Prediction** — working title in manuscript files only.\n2. **Candidate-Adaptive Structural Routing for Hypergraph-Aware Link Prediction**\n3. **Hyperedge-Pair Context and Dynamic Structural Routing for Link Prediction**\n\nThe title remains open for author decision; option 1 is not final.\n''',encoding='utf-8')
(O/'DSR_CLAIM_EVIDENCE_MATRIX.md').write_text('''# DSR claim–evidence matrix\n\n| Claim | Evidence | Boundary / status |\n|---|---|---|\n| R-HSPE improves strong NCN/NCNC hosts on Cora and PubMed under frozen V17.4. | Stored paired scalar results: NCNC ΔMRR +0.025853 (Cora, 5/5) and +0.007137 (PubMed, 5/5); NCN results are in the inherited manuscript Table 3. | Historical test summaries reused; no test artifact opened for this writing task. Protocol-specific, not universal. Innovation 1 frozen. |\n| DSR has a PubMed validation gain over fixed equal-weight R/G/P. | Phase B A6−A4 +0.00440995 MRR, 4/5 wins; inner PubMed A6−A4 +0.00132432, 2/3. | Replicated against A4 fixed blend, not against repeated GRAPH. Inner split remains exploratory. |\n| DSR beats the repeated-GRAPH routed control. | A7 is three independently initialized GRAPH experts with candidate routing. Phase B PubMed A6−A7 = −0.00137762, 2/5; Phase A +0.00172649, 2/3; inner +0.00161579, 3/3. | Not replicated on independent seeds; claim removed. |\n| DSR improves Cora. | Phase B A6−A4 +0.00046272 (2/5), A6−A7 +0.00190467 (3/5). | Small, mixed validation evidence. |\n| DSR transfers to Citeseer. | A6−NCNC +0.00662853 MRR, SD 0.01509120, 2/3; per-seed −0.01067522, +0.01706349, +0.01349731. | Small transfer signal, not stable replication; other metrics are not uniformly improved. |\n| The router operates and does not collapse. | Target masking/symmetry/label-input checks passed; A6 collapse false on Cora/PubMed. A9 changed 77.40% and 71.70% of validation contexts, respectively. | Behavior diagnostics only; not causal specialization. |\n| DSR is a novel mixture-of-experts mechanism. | V32 explicitly did not audit novelty; softmax gating and mixture-of-experts have prior art. | Not established. |\n| This manuscript contains three new algorithms. | Current methods are R-HSPE and DSR. | False; Innovation 3 is future work, not a contribution. |\n\n## Corrected arm mapping\n\n- **A4:** fixed equal-weight R/G/P mixture; includes 83 disconnected counted parameters.\n- **A5:** global three-logit R/G/P mixture; includes 80 disconnected counted parameters.\n- **A6:** candidate-routed R/G/P.\n- **A7:** candidate-routed G/G/G repeated-GRAPH control.\n- **A9:** stratified context-correspondence shuffle.\n\nThe executed arm definitions override the task-text label attached to +0.00441. See `DSR_NUMERICAL_AUDIT.json` and `tables/dsr_per_seed_contrasts.csv` for recomputed values and per-seed evidence.\n''',encoding='utf-8')
(O/'DSR_METHOD_SOURCE_AUDIT.md').write_text('''# DSR method and source audit\n\n## Workspace and provenance\n\n- Local Git root and project name: `E:/我的资料库/Documents/Downloads/DCDLP-main` / `DCDLP-main`; commit `5da7af3d282f4378b128a0ef8fb7f2e3503a9c74`.\n- The historical V32 source audit records the remote project path `/home/zhoulihui/DCDLP-main` and matched the frozen R-HSPE dependency hashes.\n- V2 uses V1's source manuscript as its base. V1 is unchanged. No workspace-info tool was available.\n\n## Authoritative sources\n\n| Item | Source | Verified detail |\n|---|---|---|\n| V32 architecture, arms, phases | `HYPERGRAPH_RESEARCH/DSR_V32/scripts/run32.py`, V32 completed per-seed JSON | Exact expert and router definitions, masks, seed phases, final-epoch checkpoint. |\n| GRAPH branch | `PAPER_SPRINT_01/scripts/sprint01.py`, reused in V32 | `[log1p(CN), CN / max(min(d_u,d_v),1)]` on target-masked raw-star unweighted two-section. |\n| PBD branch | `PBD_V30B/scripts/run30b.py`, reused in V32 | All legal simple length-three paths; symmetric inverse-Simpson effective branch counts. |\n| R-HSPE | Frozen V17 source/protocol dependencies listed in V32 `SOURCE_AUDIT.json` | 75-parameter definition unchanged. |\n| Final decision | V32 `DECISION_CORRECTION.md` | Supersedes the initial incorrect multi-source replication status. |\n\nFile SHA-256 values are recorded in `audit_sources/SOURCE_HASHES.json`; source JSON snapshots are in `audit_sources/DSR_V32/`. No model was trained by the manuscript build script.\n\n## Exact V32 method\n\nNCNC computes the host score and is not routed. Three 75-parameter slots produce residuals `Delta_R`, `Delta_G`, and `Delta_P`. The GRAPH features are target-masked projected common-neighbor count and its normalization by the smaller projected degree. PBD uses `P3 = sum_a c_u[a] = sum_b c_v[b]`, where counts enumerate valid simple paths `u-a-b-v` with four distinct vertices. `D_u=P3^2/sum_a c_u[a]^2`, `D_v=P3^2/sum_b c_v[b]^2` (both zero when P3=0); PBD is `[log1p((D_u+D_v)/2), log1p(abs(D_u-D_v))]`.
\nThe six symmetric, target-masked router inputs are, in source order: `log1p(R token count)`, `log1p(R support count)`, `log1p(P3)`, `log1p(P4)`, `log1p(deg_u+deg_v)`, and `log1p(abs(deg_u-deg_v))`. Each scaler is fitted on that seed's actual training-occurrence schedule only. Validation labels are not router inputs.

The router is `Linear(6,8) → ReLU → Linear(8,3) → softmax` (83 parameters). The final layer is zero-initialized, so initial weights equal `(1/3,1/3,1/3)`. Zero-initialized expert heads preserve the NCNC host score exactly at initialization. For each pair, `score = score_NCNC + alpha_R*Delta_R + alpha_G*Delta_G + alpha_P*Delta_P`; the alpha values sum to one. This is a soft mixture, not discrete expert selection.

A6 adds 225 expert parameters plus 83 router parameters, 308 total. A4/A5 also have 308 declared parameters, but V32 verified their disconnected pads had no gradients: A4 has an 83-parameter pad; A5 has three active global logits and an 80-parameter pad. Declared count therefore does not equal effective capacity. G/P adapters use two populated values in a six-wide input; the embedding is duplicated in mean/max slots and count slots are zero. Candidate path features are cached; path enumeration without a cache scales with enumerated simple three-hop paths. The final scalar bundle does not separately time path-cache preprocessing or isolated inference latency. V32 job-level times and peak memory are in `tables/tableS8_runtime.csv`.

## Control-label correction

The user task text attached the +0.00441 / 4-of-5 Phase B PubMed gain to “repeated GRAPH.” The executed source defines A4 as the fixed equal-weight R/G/P mixture. A7 is the actual three-GRAPH candidate-routed control. Recomputed independent-seed A6−A7 PubMed is **−0.00137762 MRR, 2/5 wins**. The positive A6−A4 value is **+0.00440995, 4/5 wins**. The V32 decision correction explains the initial aggregation bug: it promoted A7 based on another contrast nominated for the same dataset. Final status is `MULTI_SOURCE_GAIN=EXPLORATORY`. No training, score, checkpoint, or model definition changed during correction.

All 156 jobs are complete. Determinism, endpoint symmetry, candidate masking, and initialization audits passed. The first supervisor report assembly failed with `KeyError('A6')` only after jobs completed; the report was regenerated from existing scalar result records, with original failure and recovery preserved. Test was unopened and Innovation 1 was unchanged.
''',encoding='utf-8')
(O/'DSR_LIMITATIONS.md').write_text('''# Limitations and interpretation boundary\n\n1. **Validation reuse:** Phase B seeds 3–7 reuse Phase A's validation candidates; fresh seeds assess initialization/training randomness, not an independent dataset. Many previous design decisions used validation, so selection bias remains.\n2. **Small samples:** Phase A has three seeds and Phase B five. Differences and win counts are descriptive; no statistical-significance or multiplicity-corrected claim is made.\n3. **Repeated GRAPH:** PubMed A6−A7 is +0.001726 (2/3) in Phase A but −0.001378 (2/5) on new seeds. Therefore a repeated-GRAPH improvement did not replicate. The +0.004410 independent result is against A4 fixed equal-weight R/G/P.\n4. **Nominal capacity:** A4/A5 include disconnected pads with no gradients. Equal declared parameter counts do not mean equal effective function classes. The observed A6 contrasts do not isolate every optimization/capacity explanation.\n5. **Dataset dependence:** PubMed has the clearest signal; Cora effects are small/mixed. Citeseer is +0.006629 MRR vs NCNC on 2/3, not a stable transfer result. Earlier V17.4 Citeseer evidence used another protocol and is not pooled.\n6. **Router interpretation:** A6 weights vary across R-token/P3 strata and do not collapse, but these retrospective groupings are descriptive, not causal attribution.\n7. **Prior art and information:** Softmax mixture-of-experts is established. PBD's effective branch count is inverse-Simpson/Hill order 2, also established. Raw-star hypergraphs are derived from the original training graph. Prior theory distinguishes R-HSPE from the exact unweighted projection, not from the full source graph or every weighted representation.\n8. **Scope:** V32 uses five epochs, a fixed final checkpoint, and sampled 1:20 evaluation. Hits@20 can saturate and CE depends on sampled prevalence. No SOTA, all-node retrieval, native-hypergraph information, or universal generalization claim is made.\n9. **Cost:** DSR adds 308 declared parameters; candidate feature construction is cached. Separate path-preprocessing cost and per-query latency are not reported. Job time/peak GPU memory are context, not isolated router overhead.\n10. **Novelty:** V32 did not perform an exhaustive priority search for the complete DSR combination. Novelty is not confirmed by the reported performance.\n11. **Recovery provenance:** V32's first report aggregation failed with `KeyError('A6')` after training; finalization was rerun from existing scalar JSON with no retraining.\n\n**Status:** Innovation 1, R-HSPE, is frozen. Innovation 2, DSR, is provisional/performance-supported. Mechanism 2 is partially resolved/exploratory. Innovation 3 is not yet defined.\n''',encoding='utf-8')
(O/'FINAL_WRITING_REPORT.md').write_text('''# Final writing report — R-HSPE + DSR manuscript V2\n\n## Deliverables\n\n- `manuscript.source.md`, readable `manuscript.md`, `main.tex`, and `references.bib`.\n- Figure 5: editable `figures/figure5.drawio`, plus SVG/PDF/PNG exports and visual specification/review notes.\n- DSR main table, full metrics, paired per-seed contrasts, router diagnostics, and numerical audit.\n- Claim-evidence matrix, method/source audit, limitations, three title options, source hashes, and curated V32 result snapshots.\n- DOCX and PDF will be generated and visually checked after source assembly.\n\n## Research status\n\n- INNOVATION 1: R-HSPE / FROZEN.\n- INNOVATION 2: DSR / PROVISIONAL / PERFORMANCE-SUPPORTED.\n- MECHANISM 2: PARTIALLY RESOLVED / EXPLORATORY.\n- INNOVATION 3: NOT YET DEFINED; excluded from current contribution claims.\n\nThe PubMed +0.00440995 (4/5) replication is against A4 fixed equal-weight R/G/P. The executed A7 repeated-GRAPH contrast is −0.00137762 (2/5). All manuscript and audit text keeps these controls separate. DSR is not claimed to consistently beat all fixed fusion or repeated GRAPH; router behavior is not called causal; no SOTA/universal claim is made. Citeseer is a small transfer signal. The title remains undecided (option 1 is a working title).\n\n## Integrity boundary\n\nNo new model training was run. No test data or test results were opened for this task. Historical V17.4 test summaries already present in the verified V1 source were carried forward without accessing test artifacts. Innovation 1, V1, and historical experiment outputs were not modified. V32's post-training `KeyError('A6')` and recovery from existing scalar JSON are disclosed.\n\n## Numerical/source audit\n\nV32 result JSON files are complete and validation-only. Paired contrasts and wins were recomputed from the per-seed scalar records; the corrected A4/A7 values were asserted before writing. Full provenance is retained in `DSR_NUMERICAL_AUDIT.json` and `audit_sources/`. The corrected overall status is `DYNAMIC_ROUTING_GAIN=REPLICATED` only for the nominated fixed-mixture contrast; `MULTI_SOURCE_GAIN=EXPLORATORY`, with comparator named throughout this manuscript.\n''',encoding='utf-8')
paths={'V32 runner':'HYPERGRAPH_RESEARCH/DSR_V32/scripts/run32.py','PBD V30B runner':'HYPERGRAPH_RESEARCH/PBD_V30B/scripts/run30b.py','PAPER-SPRINT GRAPH source':'HYPERGRAPH_RESEARCH/PAPER_SPRINT_01/scripts/sprint01.py','frozen R-HSPE source':'HYPERGRAPH_RESEARCH/HSPE_V17_1/scripts/hspe_v17_1.py','V1 source manuscript':'PAPER_PREP/R_HSPE_MANUSCRIPT_V1/manuscript.source.md'}
h={k:{'path':v,'sha256':hashlib.sha256((R/v).read_bytes()).hexdigest()} for k,v in paths.items()}
(O/'audit_sources/SOURCE_HASHES.json').write_text(json.dumps(h,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
items=[{'path':p.name,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size} for p in sorted(AD.iterdir()) if p.is_file()]
(AD/'MANIFEST.json').write_text(json.dumps(items,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
print('Research audit documents written')

